// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	BasicAuthScopes = "BasicAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Amount      *string             `json:"amount,omitempty"`
	Category    *string             `json:"category,omitempty"`
	Date        *openapi_types.Date `json:"date,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *string             `json:"id,omitempty"`
	Subcategory *string             `json:"subcategory,omitempty"`
}

// Category defines model for Category.
type Category = string

// DateFrom defines model for DateFrom.
type DateFrom = openapi_types.Date

// DateUntil defines model for DateUntil.
type DateUntil = openapi_types.Date

// DescrLike defines model for DescrLike.
type DescrLike = string

// PageLimit defines model for PageLimit.
type PageLimit = int

// PageOffset defines model for PageOffset.
type PageOffset = int

// State defines model for State.
type State = string

// Subcategory defines model for Subcategory.
type Subcategory = string

// N400Error defines model for 400Error.
type N400Error = Error

// N500Error defines model for 500Error.
type N500Error = Error

// GetApiTransactionsParams defines parameters for GetApiTransactions.
type GetApiTransactionsParams struct {
	// DateFrom Earliest date for which results should be reported
	DateFrom *DateFrom `form:"dateFrom,omitempty" json:"dateFrom,omitempty"`

	// DateUntil Earliest date for which results should not be reported
	DateUntil *DateUntil `form:"dateUntil,omitempty" json:"dateUntil,omitempty"`

	// Category Filter by exact match on category
	Category *Category `form:"category,omitempty" json:"category,omitempty"`

	// Subcategory Filter by exact match on subcategory
	Subcategory *Subcategory `form:"subcategory,omitempty" json:"subcategory,omitempty"`

	// DescrLike Filter by matching description (SQL LIKE pattern)
	DescrLike *DescrLike `form:"descrLike,omitempty" json:"descrLike,omitempty"`

	// State Filter by exact match on state
	State *State `form:"state,omitempty" json:"state,omitempty"`

	// Limit Limits the number of items on a page
	Limit *PageLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Specifies the page number to be displayed
	Offset *PageOffset `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostApiTransactionsJSONRequestBody defines body for PostApiTransactions for application/json ContentType.
type PostApiTransactionsJSONRequestBody = Transaction

// PostApiTransactionsIdJSONRequestBody defines body for PostApiTransactionsId for application/json ContentType.
type PostApiTransactionsIdJSONRequestBody = Transaction

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApiTransactions request
	GetApiTransactions(ctx context.Context, params *GetApiTransactionsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiTransactions request with any body
	PostApiTransactionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiTransactions(ctx context.Context, body PostApiTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiTransactionsId request
	DeleteApiTransactionsId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiTransactionsId request with any body
	PostApiTransactionsIdWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiTransactionsId(ctx context.Context, id string, body PostApiTransactionsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApiTransactions(ctx context.Context, params *GetApiTransactionsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiTransactionsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiTransactionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiTransactionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiTransactions(ctx context.Context, body PostApiTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiTransactionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApiTransactionsId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiTransactionsIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiTransactionsIdWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiTransactionsIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiTransactionsId(ctx context.Context, id string, body PostApiTransactionsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiTransactionsIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiTransactionsRequest generates requests for GetApiTransactions
func NewGetApiTransactionsRequest(server string, params *GetApiTransactionsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/transactions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.DateFrom != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "dateFrom", runtime.ParamLocationQuery, *params.DateFrom); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.DateUntil != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "dateUntil", runtime.ParamLocationQuery, *params.DateUntil); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.Category != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "category", runtime.ParamLocationQuery, *params.Category); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.Subcategory != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "subcategory", runtime.ParamLocationQuery, *params.Subcategory); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.DescrLike != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "descrLike", runtime.ParamLocationQuery, *params.DescrLike); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.State != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "state", runtime.ParamLocationQuery, *params.State); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.Limit != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.Offset != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiTransactionsRequest calls the generic PostApiTransactions builder with application/json body
func NewPostApiTransactionsRequest(server string, body PostApiTransactionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiTransactionsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiTransactionsRequestWithBody generates requests for PostApiTransactions with any type of body
func NewPostApiTransactionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/transactions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteApiTransactionsIdRequest generates requests for DeleteApiTransactionsId
func NewDeleteApiTransactionsIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/transactions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiTransactionsIdRequest calls the generic PostApiTransactionsId builder with application/json body
func NewPostApiTransactionsIdRequest(server string, id string, body PostApiTransactionsIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiTransactionsIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPostApiTransactionsIdRequestWithBody generates requests for PostApiTransactionsId with any type of body
func NewPostApiTransactionsIdRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/transactions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetApiTransactions request
	GetApiTransactionsWithResponse(ctx context.Context, params *GetApiTransactionsParams, reqEditors ...RequestEditorFn) (*GetApiTransactionsResponse, error)

	// PostApiTransactions request with any body
	PostApiTransactionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiTransactionsResponse, error)

	PostApiTransactionsWithResponse(ctx context.Context, body PostApiTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiTransactionsResponse, error)

	// DeleteApiTransactionsId request
	DeleteApiTransactionsIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteApiTransactionsIdResponse, error)

	// PostApiTransactionsId request with any body
	PostApiTransactionsIdWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiTransactionsIdResponse, error)

	PostApiTransactionsIdWithResponse(ctx context.Context, id string, body PostApiTransactionsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiTransactionsIdResponse, error)
}

type GetApiTransactionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Transaction
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetApiTransactionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiTransactionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiTransactionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r PostApiTransactionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiTransactionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteApiTransactionsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeleteApiTransactionsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiTransactionsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiTransactionsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r PostApiTransactionsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiTransactionsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetApiTransactionsWithResponse request returning *GetApiTransactionsResponse
func (c *ClientWithResponses) GetApiTransactionsWithResponse(ctx context.Context, params *GetApiTransactionsParams, reqEditors ...RequestEditorFn) (*GetApiTransactionsResponse, error) {
	rsp, err := c.GetApiTransactions(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiTransactionsResponse(rsp)
}

// PostApiTransactionsWithBodyWithResponse request with arbitrary body returning *PostApiTransactionsResponse
func (c *ClientWithResponses) PostApiTransactionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiTransactionsResponse, error) {
	rsp, err := c.PostApiTransactionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiTransactionsResponse(rsp)
}

func (c *ClientWithResponses) PostApiTransactionsWithResponse(ctx context.Context, body PostApiTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiTransactionsResponse, error) {
	rsp, err := c.PostApiTransactions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiTransactionsResponse(rsp)
}

// DeleteApiTransactionsIdWithResponse request returning *DeleteApiTransactionsIdResponse
func (c *ClientWithResponses) DeleteApiTransactionsIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteApiTransactionsIdResponse, error) {
	rsp, err := c.DeleteApiTransactionsId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiTransactionsIdResponse(rsp)
}

// PostApiTransactionsIdWithBodyWithResponse request with arbitrary body returning *PostApiTransactionsIdResponse
func (c *ClientWithResponses) PostApiTransactionsIdWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiTransactionsIdResponse, error) {
	rsp, err := c.PostApiTransactionsIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiTransactionsIdResponse(rsp)
}

func (c *ClientWithResponses) PostApiTransactionsIdWithResponse(ctx context.Context, id string, body PostApiTransactionsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiTransactionsIdResponse, error) {
	rsp, err := c.PostApiTransactionsId(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiTransactionsIdResponse(rsp)
}

// ParseGetApiTransactionsResponse parses an HTTP response from a GetApiTransactionsWithResponse call
func ParseGetApiTransactionsResponse(rsp *http.Response) (*GetApiTransactionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiTransactionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Transaction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiTransactionsResponse parses an HTTP response from a PostApiTransactionsWithResponse call
func ParsePostApiTransactionsResponse(rsp *http.Response) (*PostApiTransactionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiTransactionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseDeleteApiTransactionsIdResponse parses an HTTP response from a DeleteApiTransactionsIdWithResponse call
func ParseDeleteApiTransactionsIdResponse(rsp *http.Response) (*DeleteApiTransactionsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiTransactionsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePostApiTransactionsIdResponse parses an HTTP response from a PostApiTransactionsIdWithResponse call
func ParsePostApiTransactionsIdResponse(rsp *http.Response) (*PostApiTransactionsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiTransactionsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/transactions)
	GetApiTransactions(ctx echo.Context, params GetApiTransactionsParams) error

	// (POST /api/transactions)
	PostApiTransactions(ctx echo.Context) error
	// Deletes a transaction by ID
	// (DELETE /api/transactions/{id})
	DeleteApiTransactionsId(ctx echo.Context, id string) error

	// (POST /api/transactions/{id})
	PostApiTransactionsId(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetApiTransactions converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiTransactions(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiTransactionsParams
	// ------------- Optional query parameter "dateFrom" -------------

	err = runtime.BindQueryParameter("form", true, false, "dateFrom", ctx.QueryParams(), &params.DateFrom)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dateFrom: %s", err))
	}

	// ------------- Optional query parameter "dateUntil" -------------

	err = runtime.BindQueryParameter("form", true, false, "dateUntil", ctx.QueryParams(), &params.DateUntil)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dateUntil: %s", err))
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameter("form", true, false, "category", ctx.QueryParams(), &params.Category)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category: %s", err))
	}

	// ------------- Optional query parameter "subcategory" -------------

	err = runtime.BindQueryParameter("form", true, false, "subcategory", ctx.QueryParams(), &params.Subcategory)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter subcategory: %s", err))
	}

	// ------------- Optional query parameter "descrLike" -------------

	err = runtime.BindQueryParameter("form", true, false, "descrLike", ctx.QueryParams(), &params.DescrLike)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter descrLike: %s", err))
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", ctx.QueryParams(), &params.State)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetApiTransactions(ctx, params)
	return err
}

// PostApiTransactions converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiTransactions(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostApiTransactions(ctx)
	return err
}

// DeleteApiTransactionsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApiTransactionsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteApiTransactionsId(ctx, id)
	return err
}

// PostApiTransactionsId converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiTransactionsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostApiTransactionsId(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/transactions", wrapper.GetApiTransactions)
	router.POST(baseURL+"/api/transactions", wrapper.PostApiTransactions)
	router.DELETE(baseURL+"/api/transactions/:id", wrapper.DeleteApiTransactionsId)
	router.POST(baseURL+"/api/transactions/:id", wrapper.PostApiTransactionsId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RWUW/jNgz+K4K2hw0wzrnt9pK33tobghVYt9yeij4oMpPoZks6kuoaFP7vg6TUsRMn",
	"TYtuwN4SixI/8iM/8lFq13hnwTLJ6aP0ClUDDJj+/awYVg438XcFpNF4Ns7KqfxkagYUi42AB6VZNIr1",
	"Wjgr9NOVQppo+DVA+mNVA3Iqe8ek19Co+DRvfDwjRmNXsm0LeakYPqFrDh1fKawNEItKMYilQ/H32ui1",
	"QKBQMwlau1BXYgECwTtkqI4gqZ5c9JEsHTaKt6eyOILsT8umfjU06/hMeNnPC/FFSNfmLzjFWWLL2JXo",
	"GYjv5r9fi+vZr1fCK2ZA+/0xaJ2L0yTeqBVcm8bwIZT0mQSvQdjQLACFWwrD0FCsISW8WsER73V6ccSz",
	"sQwrwM71b8slwYjvuQdtlgay++jpCQO7SExlyNdqc5QZl999BsGcI0Pn9w1xZnTM49PZqWTPw0K/vFup",
	"d+uI74HFcQRtIRHIO0uQpOPDZHKF6DD+1s4y2ESF8r42WkVc5ReK4B57j36LsJRT+U25E6Uyn1KZX0uO",
	"hsHN7L2qTSUQvgYglm0hf/rPnM8B7wEFbM+fMpRS0EHw6Dwgm5yZBohieY/SGIMwCJWc3naGd12fu8UX",
	"0CnCz6gsKZ1R7HtQjQs54j0HhezXyMFhtS3ZZ1RmLwcjD5lq9DMNa/Qw+r0w4xXQAQ1v5jGtObqPioy+",
	"CLzu6It3FvHrDuua2We+jF26w474BVgoW4ngk1grrWPKRDSOsUejQrLhOj52kU9JXNzMZCHvASm/8v7d",
	"5N0kRuY8WOWNnMof06dCesXrBLdU3pS8oyt9XI0J0x/AAS0JJWpDHBVxcC15wYRtVuUQLrz5PDTpz+/b",
	"8ZremZTdmG2Ls2zzQDrDuFsczrDtK9c5OLrpc87bSTnPMNzNqjONt9OlvdvTvR8mkxepThp6z8lPv9t3",
	"baIQ1WZUlILWQLQMdb0RmKoKqmNl1RZRq48h6GIrO0HP+vr8hU6EE0LvaGwPAI71HghQGEuALBx2TdkH",
	"elD+N45G6n87BD66avNm4j/I/lCkGQO04xVwghKNoBiqXahVWkV4yPILWUnIDsSmfDRVm+HUMLaQ5O+R",
	"BDJ2VQ9QiIWiCNMmeLNLQSEmMW1GQzIu0yt7dMyqQ0HaG92Xe+UYV7At0u06EnV0t42YSu6n/9RSctic",
	"Hw4z4IG3Pqs825Yq1Pzvrw7BwoMHHdnvrQ+haVQcj9uU0rAL4go3u5Rn9dNru+iVtGV3b0fb/6CP37R5",
	"e8tOSnlvzbm9iymhtGpmPgLW2yWHpmUJD6rxNbwzrrx/L9u79p8AAAD//50bX1TWDwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
