openapi: 3.0.0
info:
  version: 1.0.0
  title: Accounts API
  description: Get and update account information

servers:
  - url: https://example.io/v1

security:
  - BasicAuth: []

paths:
  /transactions:
    get:
      description: Returns a list of transactions
      parameters:
        - $ref: '#/components/parameters/DateFrom'
        - $ref: '#/components/parameters/DateUntil'
        - $ref: '#/components/parameters/Category'
        - $ref: '#/components/parameters/Subcategory'
        - $ref: '#/components/parameters/DescrLike'
        - $ref: '#/components/parameters/State'
        - $ref: '#/components/parameters/PageLimit'
        - $ref: '#/components/parameters/PageOffset'
      responses:
        '200':
          description: Successfully returned a list of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/500Error'

    post:
      description: Lets a user insert or update a transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Successfully created or updated the transaction
        '400':
          $ref: '#/components/responses/400Error'

  /transactions/{id}:
    post:
      description: Lets a user update a transaction
      parameters:
        - name: id
          in: path
          description: ID of transaction to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Successfully updated the transaction
        '400':
          $ref: '#/components/responses/400Error'
    delete:
      summary: Deletes a transaction by ID
      description: deletes a single transaction based on the ID supplied
      parameters:
        - name: id
          in: path
          description: ID of transaction to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: pet deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    Transaction:
      type: object
      properties:
        id:
          type: string
        date:
            type: string
            format: date
        description:
            type: string
        amount:
            type: string
        category:
            type: string
        subcategory:
            type: string

  parameters:
    DateFrom:
      name: dateFrom
      in: query
      description: Earliest date for which results should be reported
      schema:
        type: string
        format: date
      
    DateUntil:
      name: dateUntil
      in: query
      description: Earliest date for which results should not be reported
      schema:
        type: string
        format: date
      
    DescrLike:
      name: descrLike
      in: query
      description: Filter by matching description (SQL LIKE pattern)
      schema:
        type: string
      
    Category:
      name: category
      in: query
      description: Filter by exact match on category
      schema:
        type: string
      
    Subcategory:
      name: subcategory
      in: query
      description: Filter by exact match on subcategory
      schema:
        type: string
      
    State:
      name: state
      in: query
      description: Filter by exact match on state
      schema:
        type: string
      
    PageLimit:
      name: limit
      in: query
      description: Limits the number of items on a page
      schema:
        type: integer
      
    PageOffset:
      name: offset
      in: query
      description: Specifies the page number to be displayed
      schema:
        type: integer

  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    500Error:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
